### ISSUE TITLE
Handwritten OCR?

### ISSUE THREAD

**Issue by LightTemplar** [crelder/zettelkasten#6]
Do you OCR your Notes? If yes, what do you use for it?

**Comment by crelder** [comment]
No, I don't use OCR, since it detects my handwriting very poorly. 

I use meta data like the context/source or a keyword to find relevant notes. 

Also every zettel has a predecessor. So using the index I can enter lines of thoughts.

I use GoodNotes for writing handwritten notes on my iPad. But mostly I write them on paper or as a .txt file now.
